language: node_js
node_js:
  - 'lts/*'
cache: yarn
jobs:
  include:
    - stage: Build
      script: yarn build
    - stage: Deploy to GitHub Pages
      script: skip
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        verbose: true
        keep-history: true
        committer-from-gh: true
        target-branch: master
        on:
          branch: dev