language: node_js
node_js:
  - 'lts/*'
cache: yarn
script: yarn test && yarn build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  keep-history: true
  committer-from-gh: true
  target-branch: master
  on:
    branch: dev